### ISSUE TITLE
Not able to connect to remote Jupyter Notebook from Jupyterhub

### ISSUE THREAD

**Issue by pawannrao-ebay** [jupyter/jupyterhub#404] opened 2016-01-29 23:14 UTC
I am spawning a remote notebook on a docker container and passing the IP and port info to the spawner class, but I m not able to connect to it eventhough all the config seems right from jupyterhub and jupyter notebook stand point. I have done all the essentials like allowing all ips, trusting x-header configuration etc. Let me know if you can make sense out of this error.

The curl also works for the remote notebook:(curl http://172.20.193.152:9009)

[I 2016-01-29 23:09:20.490 JupyterHub base:281] User test1 server took 83.033 seconds to start
[I 2016-01-29 23:09:20.491 JupyterHub orm:170] Adding user test1 to proxy /user/test1 => http://172.20.193.152:9009
[I 2016-01-29 23:09:20.511 JupyterHub log:100] 302 GET /hub/user/test1/ (test1@10.65.63.36) 83078.03ms
[I 2016-01-29 23:09:20.745 JupyterHub log:100] 302 GET /static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (@10.65.63.36) 3.30ms
[I 2016-01-29 23:09:20.767 JupyterHub log:100] 302 GET /custom/custom.css (@10.65.63.37) 1.97ms
[I 2016-01-29 23:09:20.774 JupyterHub log:100] 302 GET /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@10.65.63.36) 0.68ms
[I 2016-01-29 23:09:20.786 JupyterHub log:100] 302 GET /static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@10.65.63.39) 0.67ms
[I 2016-01-29 23:09:20.792 JupyterHub log:100] 302 GET /static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@10.65.63.41) 0.70ms
[I 2016-01-29 23:09:20.801 JupyterHub log:100] 302 GET /static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@10.65.63.40) 0.69ms
[W 2016-01-29 23:09:20.811 JupyterHub log:100] 404 GET /hub/custom/custom.css (test1@10.65.63.37) 3.29ms
[W 2016-01-29 23:09:20.813 JupyterHub log:100] 404 GET /hub/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (@10.65.63.36) 0.51ms
[W 2016-01-29 23:09:20.814 JupyterHub log:100] 404 GET /hub/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (@10.65.63.39) 0.47ms
[W 2016-01-29 23:09:20.836 JupyterHub log:100] 404 GET /hub/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (@10.65.63.41) 0.68ms
[W 2016-01-29 23:09:20.841 JupyterHub log:100] 404 GET /hub/static/style/style.min.css?v=807166c81ded9672f91872a576572dcd (@10.65.63.40) 0.55ms
[I 2016-01-29 23:09:20.910 JupyterHub log:100] 302 GET /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@10.65.63.36) 0.85ms
[W 2016-01-29 23:09:20.940 JupyterHub log:100] 404 GET /hub/static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@10.65.63.36) 0.71ms

**Comment by pawannrao-ebay** [comment] 2016-01-29 23:18
This is my version of the edited jupyter notebook conf file, rest of the options have been kept default.

# Whether to open in a browser after starting. The specific browser used is
# platform dependent and determined by the python standard library `webbrowser`
# module, unless it is overridden using the --browser (NotebookApp.browser)
# configuration option.
c.NotebookApp.open_browser = False

# Python modules to load as notebook server extensions. This is an experimental
# API, and may change in future releases.
# c.NotebookApp.server_extensions = traitlets.Undefined

# The IP address the notebook server will listen on.
c.NotebookApp.ip = '*'

# Set the Access-Control-Allow-Origin header
# 
# Use '*' to allow any origin to access your server.
# 
# Takes precedence over allow_origin_pat.
c.NotebookApp.allow_origin = '*'

# Extra paths to search for serving jinja templates.
# 
# Can be used to override templates from notebook.templates.
# c.NotebookApp.extra_template_paths = traitlets.Undefined

# The base URL for websockets, if it differs from the HTTP server (hint: it
# almost certainly doesn't).
# 
# Should be in the form of an HTTP origin: ws[s]://hostname[:port]
# c.NotebookApp.websocket_url = ''

# Supply overrides for the tornado.web.Application that the IPython notebook
# uses.
# c.NotebookApp.tornado_settings = traitlets.Undefined

# The file where the cookie secret is stored.
# c.NotebookApp.cookie_secret_file = ''

# The full path to a private key file for usage with SSL/TLS.
# c.NotebookApp.keyfile = ''

# 
# c.NotebookApp.file_to_run = ''

# Reraise exceptions encountered loading server extensions?
# c.NotebookApp.reraise_server_extension_failures = False

# The directory to use for notebooks and kernels.
# c.NotebookApp.notebook_dir = ''

# Whether to trust or not X-Scheme/X-Forwarded-Proto and X-Real-Ip/X-Forwarded-
# For headerssent by the upstream reverse proxy. Necessary if the proxy handles
# SSL
c.NotebookApp.trust_xheaders = True 

# extra paths to look for Javascript notebook extensions
# c.NotebookApp.extra_nbextensions_path = traitlets.Undefined

# The session manager class to use.
# c.NotebookApp.session_manager_class = <class 'notebook.services.sessions.sessionmanager.SessionManager'>

# Whether to enable MathJax for typesetting math/TeX
# 
# MathJax is the javascript library IPython uses to render math/LaTeX. It is
# very large, so you may want to disable it if you have a slow internet
# connection, or for offline use of the notebook.
# 
# When disabled, equations etc. will appear as their untransformed TeX source.
# c.NotebookApp.enable_mathjax = True

# The config manager class to use
# c.NotebookApp.config_manager_class = <class 'notebook.services.config.manager.ConfigManager'>

# Supply extra arguments that will be passed to Jinja environment.
# c.NotebookApp.jinja_environment_options = traitlets.Undefined

# The notebook manager class to use.
# c.NotebookApp.contents_manager_class = <class 'notebook.services.contents.filemanager.FileContentsManager'>

# The full path to an SSL/TLS certificate file.
#c.NotebookApp.certfile = '/krylov/workspace/mycert.pem'

# The url for MathJax.js.
# c.NotebookApp.mathjax_url = ''

# Extra paths to search for serving static files.
# 
# This allows adding javascript/css to be available from the notebook server
# machine, or overriding individual files in the IPython
# c.NotebookApp.extra_static_paths = traitlets.Undefined

# Specify what command to use to invoke a web browser when opening the notebook.
# If not specified, the default browser will be determined by the `webbrowser`
# standard library module, which allows setting of the BROWSER environment
# variable to override it.
# c.NotebookApp.browser = ''

# DEPRECATED use base_url
# c.NotebookApp.base_project_url = '/'

# Hashed password to use for web authentication.
# 
# To generate, type in a python/IPython shell:
# 
#   from notebook.auth import passwd; passwd()
# 
# The string should be of the form type:salt:hashed-password.
# c.NotebookApp.password = 'sha1:7eaa9db40370:49c855f6fe82082d932248f1fd0e7a0a9f6a41ea'

# The kernel manager class to use.
# c.NotebookApp.kernel_manager_class = <class 'notebook.services.kernels.kernelmanager.MappingKernelManager'>

# The random bytes used to secure cookies. By default this is a new random
# number every time you start the Notebook. Set it to a value in a config file
# to enable logins to persist across server sessions.
# 
# Note: Cookie secrets should be kept private, do not share config files with
# cookie_secret stored in plaintext (you can read the value from a file).
# c.NotebookApp.cookie_secret = b''

# Supply SSL options for the tornado HTTPServer. See the tornado docs for
# details.
# c.NotebookApp.ssl_options = traitlets.Undefined

# The port the notebook server will listen on.
c.NotebookApp.port = 9009

**Comment by willingc** [comment] 2016-02-01 21:08
@pawannrao-ebay Try using ``c.NotebookApp.ip='0.0.0.0'`` or replacing `'*'` with `''`. See issue #406 and PR #407. 

cc/@minrk

**Comment by minrk** [comment] 2016-02-02 08:09
A duplicate of this issue was opened at jupyter/notebook#1027, and has been closed.

**Closed by minrk** 2016-02-02 08:09 UTC
