### ISSUE TITLE
PAM authentication issue

### ISSUE THREAD

**Issue by adamkovics** [jupyter/jupyterhub#319] opened 2015-10-05 16:33 UTC
I prematurely closed #318, (see 2 below) and PAM authentication remains an issue.

Some other symptoms/behaviors:

1) user remains logged in while interrupting and restarting JupyterHub (no login required after hub restart). Not sure that this is unintended, just sayin.

2) in the situation above (restarting JupyterHub after interupt, with user remaining logged in by default) allows for one subsequent login after logout. But only one.

3) logging out after login results in PAM error on subsequent login.

Seems like it should be relatively easy to reproduce/confirm if it's not peculiar to running on OS X, or my particular settings.

**Comment by minrk** [comment] 2015-10-05 20:59
> user remains logged in while interrupting and restarting JupyterHub (no login required after hub restart). 

Yes, that's intended. Restarting the Hub shouldn't have any effect on who is logged in; that state is persisted to the database. If you clear the login state of the Hub, users will be logged out, but restarting does not do this.

My guess is the other issues are related to the recent session changes, where it opens a PAM session but doesn't close it. I cannot actually reproduce the issue, though. What system are you running on with what config? I've tested current master on OS X and Linux with no issues so far. Is yours a managed system that might do clever things on login?

**Comment by adamkovics** [comment] 2015-10-05 21:15
Thanks for checking. I'm running OS X 10.10.5 out of the box, without any management. 

Just checked that jupyterhub is current:

haze:~/python/jupyterhub$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

Also checked on pamela:

haze:~/python/pamela$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

Here's my config, also seemingly straightforward. 

c = get_config()
c.JupyterHub.ssl_key = '/path/to/key'
c.JupyterHub.cookie_secret_file = '/path/to/jupyterhub_cookie_secret'
c.JupyterHub.ssl_cert = '/path/to/cert'
c.JupyterHub.port = 443
c.Authenticator.whitelist = {'mate','jt',}
c.Authenticator.admin_users = {'mate'}

**Comment by minrk** [comment] 2016-01-25 12:02
PAM sessions are now closed in single-user shutdown

**Closed by minrk** 2016-01-25 12:02 UTC
